"""Discover task definitions and validate their referenced component IDs."""

from __future__ import annotations

from dataclasses import dataclass
from functools import cache
from importlib.resources import files
from importlib.resources.abc import Traversable

from judgearena.benchmarks.pairwise.scoring import PAIRWISE_SCORER_NAMES
from judgearena.prompts.registry import JUDGE_PROMPT_PRESETS
from judgearena.tasks.loader import TaskDefinitionError, TaskLoader
from judgearena.tasks.schema import ResolvedTaskSpec, TaskSelection


@dataclass(frozen=True)
class AdapterCatalog:
    """Component IDs that task YAML files may reference."""

    runners: frozenset[str] = frozenset({"mt_bench", "pairwise"})
    datasets: frozenset[str] = frozenset(
        {"arena_hard", "judgearena_tables", "m_arena_hard", "mt_bench"}
    )
    prompts: frozenset[str] = frozenset(JUDGE_PROMPT_PRESETS)
    scorers: frozenset[str] = PAIRWISE_SCORER_NAMES


def load_tasks(
    definitions_root: Traversable | None = None,
    *,
    adapters: AdapterCatalog | None = None,
) -> dict[str, ResolvedTaskSpec]:
    """Discover, validate, and return all packaged tasks keyed by task ID.

    With no arguments this reads JudgeArena's installed definitions and caches
    the result. An explicit ``definitions_root`` (used by tests) is never cached.
    """
    if definitions_root is None and adapters is None:
        return _load_packaged_tasks()
    root = definitions_root or files("judgearena.tasks").joinpath("definitions")
    return _discover_tasks(root, adapters or AdapterCatalog())


@cache
def _load_packaged_tasks() -> dict[str, ResolvedTaskSpec]:
    root = files("judgearena.tasks").joinpath("definitions")
    return _discover_tasks(root, AdapterCatalog())


def _discover_tasks(
    definitions_root: Traversable, adapters: AdapterCatalog
) -> dict[str, ResolvedTaskSpec]:
    loader = TaskLoader(definitions_root)
    tasks: dict[str, ResolvedTaskSpec] = {}
    for relative_path in loader.discover():
        resolved = loader.load(relative_path)
        if resolved.task in tasks:
            other = tasks[resolved.task].provenance.source_path
            raise TaskDefinitionError(
                f"Duplicate task ID {resolved.task!r} in {other} and {relative_path}"
            )
        _validate_adapter_ids(resolved, adapters)
        tasks[resolved.task] = resolved
    _validate_variant_ids(tasks)
    return dict(sorted(tasks.items()))


def _validate_adapter_ids(resolved: ResolvedTaskSpec, adapters: AdapterCatalog) -> None:
    spec = resolved.spec
    references = {
        "runner": (spec.protocol.runner, adapters.runners),
        "dataset adapter": (spec.dataset.adapter, adapters.datasets),
        "prompt": (spec.protocol.judge.default_prompt, adapters.prompts),
        "scorer": (spec.protocol.scoring.adapter, adapters.scorers),
    }
    for kind, (adapter_id, available) in references.items():
        if adapter_id not in available:
            raise TaskDefinitionError(
                f"{resolved.provenance.source_path}: unknown {kind} {adapter_id!r}"
            )


def _validate_variant_ids(tasks: dict[str, ResolvedTaskSpec]) -> None:
    """Reject a family-variant ID that collides with a real task or each other."""
    aliases: dict[str, str] = {}
    for task_id, resolved in tasks.items():
        variants = resolved.spec.variants
        if variants is None:
            continue
        for suffix in (*variants.values, *variants.groups):
            alias = f"{task_id}-{suffix}"
            if alias in tasks:
                raise TaskDefinitionError(
                    f"Variant {alias!r} from {task_id!r} collides with an "
                    "existing task of the same ID."
                )
            if alias in aliases:
                raise TaskDefinitionError(
                    f"Variant {alias!r} from {task_id!r} collides with a variant "
                    f"already generated by {aliases[alias]!r}."
                )
            aliases[alias] = task_id


def resolve_task(
    tasks: dict[str, ResolvedTaskSpec], task_id: str
) -> ResolvedTaskSpec | None:
    """Resolve ``task_id`` against ``tasks``, or ``None`` when it is unknown.

    A ``task_id`` matches either a definition directly, or a task family:
    ``family-v1-uk`` selects the ``uk`` view of the ``family-v1`` definition,
    where ``uk`` is a single value or a named group declared under ``variants``.
    """
    exact = tasks.get(task_id)
    if exact is not None:
        return exact

    # Longest definition name first, so a longer base wins over a shorter one
    # that is a prefix of it (e.g. ``a-b`` before ``a``).
    for base in sorted(tasks.values(), key=lambda t: len(t.task), reverse=True):
        variants = base.spec.variants
        if variants is None:
            continue
        prefix = f"{base.task}-"
        if not task_id.startswith(prefix):
            continue
        suffix = task_id[len(prefix) :]
        if suffix in variants.values:
            values: tuple[str, ...] = (suffix,)
        elif suffix in variants.groups:
            values = variants.groups[suffix]
        else:
            continue
        return ResolvedTaskSpec(
            spec=base.spec,
            provenance=base.provenance,
            invocation_task=task_id,
            selection=TaskSelection(
                selector=variants.selector,
                name=suffix,
                values=values,
            ),
        )
    return None


def get_packaged_task(task_id: str) -> ResolvedTaskSpec | None:
    """Look up a task from JudgeArena's installed YAML definitions.

    Family variants (e.g. ``family-v1-uk``) are resolved from their definition.
    """
    return resolve_task(load_tasks(), task_id)
